### ISSUE TITLE
Suggest a project

### ISSUE THREAD

**Issue by LlamaMB** [safe-global/safe-ecosystem-database#10]
### Project

LlamaNodes

### Description

LlamaNodes provides fast and secure access to RPC infrastructure designed for Web3 🦙

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

DeFi

### Select secondary categories of your project.

Infrastructure

### Project logo

![oXd9Gq2k_400x400](https://github.com/safe-global/safe-ecosystem-database/assets/115741159/1b617d80-f4a8-4262-be3b-ae1ffb424efa)

### Value proposition

LlamaNodes is a low-latency privacy first RPC provider - with dynamic load-balancing, autoscaling, and globally redundant infrastructure. We provide your project with industry-leading features, crypto payments, and all with no contracts.

### Contact

info@llamanodes.com

### Project URL

https://llamanodes.com/

### Github / Dev Docs

https://github.com/llamanodes

### Twitter

https://twitter.com/LlamaNodes

### Primary integration

Safe Apps SDK

### Packages

Unsure

### Smart Accounts

Yes

### Networks

Ethereum

### Can you create a Safe via the interface?

No

### Can you import an existing Safe via the interface?

No

**Comment by ennisjo** [comment]
G2G @germartinez

**Comment by LlamaMB** [comment]
Thanks guys @germartinez @ennisjo! Will LlamaNodes be reflected on the dApp Store UI by chance? Cheers!
