### ISSUE TITLE
Suggest a project

### ISSUE THREAD

**Issue by popodidi** [safe-global/safe-ecosystem-database#105]
### Project

MU Wallet

### Description

MU Wallet is a non-custodial wallet offering a seamless on-chain stablecoin earning experience, featuring passkey security, automated vaults, and on-chain DCA.

### Please provide the project scope.

Core SDK Integration

### Select a primary category of your project.

DeFi

### Select secondary categories of your project.

Yield, Automation, Wallet

### Project logo

![mu-logo](https://github.com/user-attachments/assets/e658fbb7-cf60-4cc8-b539-4ccafdf9965a)

### Value proposition

Offering best-in-class on-chain earning experience. Non-custodial, simple, mobile-first, and secure.

### Contact

hao@mu-wallet.com

### Project URL

https://mu-wallet.com

### Twitter

@muwallet_app

### Primary integration

Core SDK, Unsure

### Packages

Safe Core SDK, Unsure

### Modules / Guards

@safe-global/safe-apps-sdk
@safe-global/safe-apps-provider

(mainly from `permissionless.js`)

### Smart Accounts

Custom authorization for passkey, multi-signer for recovery backup, batch transactions for better UX

### Is Safe the only Smart Account provider you are using in your project?

Yes

### Networks

Arbitrum, Base, Ethereum, Optimism, Polygon PoS

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

No

**Comment by zzuziak** [comment]
Will be included in the next sync 👍
