### ISSUE TITLE
Add Partitura.io

### ISSUE THREAD

**Issue by axdvdv** [safe-global/safe-ecosystem-database#11]
### Project

Partitura

### Description

Partitura is the infrastructure for building composable smart transactions. With Partitura you can easily compose any action into one flow, set up an automated flow like DCA strategy, and manage your web3 routine with the power of smart accounts.

### Please provide the project scope.

Core SDK Integration

### Select a primary category of your project.

Infrastructure

### Select secondary categories of your project.

Tooling

### Project logo

![Twitter Profile (3)](https://github.com/safe-global/safe-ecosystem-database/assets/24738584/1a3f75f1-f18f-4551-a54c-bef931017b97)

### Value proposition

Partitura makes your web3 life easier with the power of smart accounts.

### Contact

hello@partitura.io

### Project URL

Partitura.io

### Github / Dev Docs

https://github.com/Partituraio

### Twitter

@partitura_io

### Primary integration

Safe Apps SDK, Core SDK, Transaction Service API, Safe Contracts

### Packages

Safe Core SDK, Safe Service Client, Safe Ethers Adapter

### Modules / Guards

- GelatoSafeModule

### Smart Accounts

We leverage batch execution of transactions and allow to users create, execute and automate their usual web3 action.

### Networks

Base, Ethereum, Gnosis Chain, Polygon, Optimism, Arbitrum

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

Yes

**Comment by germartinez** [comment]
Hi @axdvdv, could you provide a rounded image?
Thank you!

**Comment by axdvdv** [comment]
![partitura logo](https://github.com/safe-global/safe-ecosystem-database/assets/24738584/a3a1a78a-b9da-46f8-94be-9c91a713ce51)
@germartinez is it ok?

**Comment by germartinez** [comment]
@axdvdv yes, thank you!

**Comment by axdvdv** [comment]
Hi @germartinez ! Any updates?

**Comment by germartinez** [comment]
Will be released on Monday next week to be available at ecosystem.safe.global
