### ISSUE TITLE
Lore (Formerly Prysm)

### ISSUE THREAD

**Issue by MartinOnaMonday** [safe-global/safe-ecosystem-database#13]
### Project

Lore (Formerly Prysm)

### Description

Lore helps anyone spin up a group wallet, pool crypto and make any web3 transaction.

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

Collectibles / NFT

### Select secondary categories of your project.

Collectibles, DeFi, Fundraising, Accounting, Wallet

### Project logo

![Lore](https://github.com/safe-global/safe-ecosystem-database/assets/138161701/0f9ef801-c971-42e7-9d8c-c4982e1646f5)

### Value proposition

Lore (previously Prysm) is the co-ownership platform. We enable communities & collectives to pool resources, collect NFTs, and use web3 together in a shared vault. We are a co-ownership framework & application built on [Gnosis Safe](https://safe.global/), a battle-tested multi-sig wallet.

### Contact

https://twitter.com/loredotxyz

### Project URL

lore.xyz

### Github / Dev Docs

https://docs.lore.xyz/

### Twitter

https://twitter.com/loredotxyz

### Primary integration

Safe Apps SDK

### Packages

Unsure

### Networks

Ethereum

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

Yes

**Comment by ennisjo** [comment]
G2G @germartinez - however, i would Lore's project scope as **Safe Interface**

Are you fine if we change from Safe App to Safe Interface @MartinOnaMonday ?

**Comment by MartinOnaMonday** [comment]
Hello,

Yes, that is ok! Thank you for checking.

Best,
Martin

**Comment by germartinez** [comment]
I removed "Gnosis" from "Gnosis Safe" in your value proposition as we have rebranded to just "Safe" :)
