### ISSUE TITLE
Suggest a project

### ISSUE THREAD

**Issue by 314yush** [safe-global/safe-ecosystem-database#14]
### Project

Bungee Exchange

### Description

Find the best route & make the jump to your favourite chains.

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

Infrastructure

### Select secondary categories of your project.

Bridge, Aggregator

### Project logo

![bungeelogo](https://github.com/safe-global/safe-ecosystem-database/assets/76194201/594fff84-dd7a-4744-af8c-a20ac1b4f81f)

### Value proposition

Bungee aggregates bridges & DEXs to get users the best routes to jump between 12+ chains.

### Project URL

bungee.exchange

### Twitter

https://twitter.com/bungeeexchange

### Networks

Ethereum, BNB, Gnosis Chain, Polygon, Optimism, Avalanche, Arbitrum, Aurora

### Can you create a Safe via the interface?

None

### Can you import an existing Safe via the interface?

None

**Comment by ennisjo** [comment]
primary integration is safe-apps-sdk. Can you amend? As this is a required field for the landing page.

**Comment by germartinez** [comment]
Hello @314yush, please review the changes here before publishing them: https://github.com/safe-global/safe-ecosystem-database/pull/27

The project was already in the Safe Ecosystem Database but is not clear if you want to remove some fields like "contact" or "github" or keep the previous data we have for them.

Thank you!

**Comment by debbchiasafe** [comment]
Project has been added to safe.global/ecosystem
