### ISSUE TITLE
qubit wallet

### ISSUE THREAD

**Issue by alina-borysenko** [safe-global/safe-ecosystem-database#23]
### Project

qubit wallet 👛🎮

### Description

A non-custodial smart contract wallet leveraging Account Abstraction and designed for web3 gamers 👛 🎮 
- 📩 Social Login & easy recovery
- 🎆 Alert & Notifications
- 💱 Session keys
- 👪 Multisig
- 😎 Fee Sponsorship (pay gas fee with any erc-20 token)
- 🖼 NFT Gallery
Qubit provides an SDK for games to easily integrate qubit's wallet and provide a smooth experience for users. 

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

Infrastructure

### Select secondary categories of your project.

Collectibles, Wallet, Gaming

### Project logo

![image1](https://github.com/safe-global/safe-ecosystem-database/assets/104866630/1a72ec3d-9d5e-4582-aeb0-c4e12fe74dd2)

### Value proposition

- **Simplified Wallet Management**: Leveraging Account Abstraction, qubit wallet addresses wallet management, one of the major pain points in gaming. It promises a smooth and secure wallet experience for gamers.
- **Easy Setup and User-Friendly Interface**: qubit wallet allows users to create a non-custodial wallet using their Gmail credentials or phone number within seconds. Users won't have to risk losing their seed phrase or access to their wallet.
- **Multi-Chain Support**: qubit wallet supports multiple networks including Ethereum, Polygon, Optimism, and Arbitrum. It offers seamless integration with games for a hassle-free gaming experience.
- **Gas Fee Sponsoring**: Users can pay transaction fees with other ERC-20 tokens besides ETH, eliminating the need to maintain an ETH balance for transaction costs. If desired, games can cover players fees.
- **Enhanced Asset Control**: qubit wallet allows users to view all their NFTs per game in their wallet, providing more control over their gaming assets.
- **Advanced Security Measures**: qubit wallet is non-custodial and uses a multi-sig approach, where three separate keys are created and at least two are needed for transaction approval. If one key is compromised, the other two can be used to regain access and regenerate the compromised key. 
- **Wallet protection**: Users can customize access levels for games using session keys.

### Contact

hello@qubitwallet.xyz

### Project URL

https://qubitwallet.xyz

### Github / Dev Docs

https://docs.qubitwallet.xyz

### Twitter

qubitwallet

### Primary integration

Safe Contracts

### Networks

Ethereum, Polygon, Optimism, Arbitrum

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

No

**Comment by ennisjo** [comment]
@alina-borysenko - could we change the Project Scope to be "Safe Interface" rather than Safe App? As generally Safe Interface's integrate directly with our core contracts and core sdk. Which I assume is what Qubit does!

**Comment by alina-borysenko** [comment]
@ennisjo sure! we integrate directly with Safe contracts. Thank you

**Comment by ennisjo** [comment]
lgtm @germartinez
