### ISSUE TITLE
Suggest a project

### ISSUE THREAD

**Issue by andfletcher** [safe-global/safe-ecosystem-database#29]
### Project

Beamer Bridge

### Description

Beam your ERC20 assets between EVM compatible rollups with certainty, speed and security.

### Please provide the project scope.

Interface

### Select a primary category of your project.

Infrastructure

### Select secondary categories of your project.

Bridge, Infrastructure, Mobile App

### Project logo

![Stacked-teal-SD](https://github.com/safe-global/safe-ecosystem-database/assets/39694712/b9f410ce-f780-46fb-8b45-c6d2e42f038a)

### Value proposition

Security of Ethereum L1: We use Ethereum L1 for messaging and settlement. Best-in-class security.

Blazing Fast: Bridge assets in as little as 2.5 seconds.

Exact amounts: If you send USDC 1,000, you always receive USDC 1,000. No funky decimals.

Easy Fees: Pay just 0.3% of the transfer amount. Charged upfront on the source rollup.

Super Simple: Sign just one transaction on the source rollup. That's it. You're done!

Canonical Tokens: You always receive canonical tokens, never derivative or proxy tokens.

Final: When you get your tokens on the destination rollups, they're 100% yours.

### Contact

hello@beamerbridge.com

### Project URL

https://beamerbridge.com

### Github / Dev Docs

https://docs.beamerbridge.com/agent.html

### Twitter

https://twitter.com/BeamerBridge

### Primary integration

Safe Apps SDK

### Smart Accounts

Safe users are able to bridge directly out of their safe vault by using the app in the Safe App dashboard: https://app.safe.global/share/safe-app?appUrl=https%3A%2F%2Fapp.beamerbridge.com&chain=eth

### Networks

Ethereum, Optimism, Arbitrum

### Can you create a Safe via the interface?

No

### Can you import an existing Safe via the interface?

No

**Comment by ennisjo** [comment]
@andfletcher - could you change the project scope to "Safe App"? "Interfaces" use the core sdk and Safe Apps use the Safe Apps sdk.

```
Please provide the project scope.
Interface
```
