### ISSUE TITLE
Attest Fest – Suggest a project

### ISSUE THREAD

**Issue by kristoferlund** [safe-global/safe-ecosystem-database#32]
### Project

Attest Fest

### Description

Creating attestations should be easy! Attest Fest is a tool that allows you to create multiple EAS attestations using only one Ethereum transaction. Attest Fest integrates with [Ethereum Attestation Service](https://attest.sh/) and [Safe multisig wallets](https://safe.global/) to enable anyone to create onchain attestations about anything, fostering a more trustful and transparent world.

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

DAO Tooling

### Select secondary categories of your project.

DAO Tooling

### Project logo

![icon](https://github.com/safe-global/safe-ecosystem-database/assets/9698363/389b3f50-dbb8-41d5-8de6-8fe73eac1410)

### Value proposition

The Ethereum Attestation Service is a great new core building block for onchain reputation, trust and more. Creating attestations is possible through the main attestation explorer as well as through apps with integrations: Gitcoin Passport, Praise etc. 

What is not currently possible at [eas](https://easscan.org/) is to batch create attestations. You can create one attestation with multiple recipients but not multiple attestations where each recipient get a unique attestation. 

Attest Fest provides this functionality. Just past a CSV file with attestation data and use the power of Safe to create a transaction batch. 

App integrates deeply with Safe, allowing the user to select Safe to use, propose/sign transaction and execute it without having to go to safe.global.

### Contact

Kristofer Lund, Twitter: @kristoferlund, Telegram: kristoferkristofer

### Project URL

https://attest-fest.party/

### Github / Dev Docs

https://github.com/kristoferlund/attest-fest

### Twitter

https://twitter.com/AttestFest

### Primary integration

Core SDK

### Packages

Safe Core SDK

### Smart Accounts

I am using the protocol kit as well as the api kit to create, sign and execute safe transactions.

### Networks

Ethereum, Optimism

### Can you create a Safe via the interface?

No

### Can you import an existing Safe via the interface?

Yes

**Comment by ennisjo** [comment]
@germartinez - this is G2G

**Comment by debbchiasafe** [comment]
Updated internal db
