### ISSUE TITLE
Suggest a project

### ISSUE THREAD

**Issue by Yoav1t** [safe-global/safe-ecosystem-database#33]
### Project

Redefine 

### Description

Redefine's DeFirewall, a pre-transaction risk assessment tool, scrutinizes every transaction before execution, acting as a powerful deterrent against the unauthorized use of funds, and giving the user an analysis and visibility of their transactions and their risks.

### Please provide the project scope.

Interface

### Select a primary category of your project.

Infrastructure

### Select secondary categories of your project.

DeFi, Institutional, Tooling

### Project logo

![RedefineLogo-B on W](https://github.com/safe-global/safe-ecosystem-database/assets/107555364/d0b565d0-53ec-434b-a96f-e89befa1e2df)

### Value proposition

This integration gives safe's users the ability to transact with more confidence by diligently checking and assessing each of their transactions.

### Contact

yoavt@redefine.net

### Project URL

https://redefine.net/

### Twitter

https://twitter.com/Redefine_crypto

### Primary integration

Transaction Service API and Safe Contracts

### Networks

Ethereum, BNB, Polygon, Avalanche, Arbitrum

### Can you create a Safe via the interface?

No

### Can you import an existing Safe via the interface?

None

**Comment by ennisjo** [comment]
@Yoav1t - could you change the "Primary Integration" to include "Transaction Service API" and "Safe Contracts"?

**Comment by Yoav1t** [comment]
done @ennisjo

**Comment by debbchiasafe** [comment]
Updated internal db
