### ISSUE TITLE
Suggest a project

### ISSUE THREAD

**Issue by luca590** [safe-global/safe-ecosystem-database#35]
### Project

DeFi Armor

### Description

DeFi Armor is a co-signer with a (simulation based) policy & execution engine built on top of Safe.

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

DeFi

### Select secondary categories of your project.

DEX, SAFE, Lending / Borrowing, Institutional, Payments, Infrastructure, Aggregator, Automation, Wallet

### Project logo

![DeFi Amor Logo Final_Transparent (2)](https://github.com/safe-global/safe-ecosystem-database/assets/4744524/7c27218e-746c-4372-8f0f-3e87c458e15a)

### Value proposition

One can use DeFi Armor as a standalone wallet or as part of their existing security setup by integrating one's custodian. What's really important, is we enable firms to separate trading and operation keys generically for DeFi, which is required in every asset class in the world except DeFi as a measure of security. We use Safe as the basis for the security architecture; the funds sit in Safe and we've built a module that checks the signatures and enables some other important features.

### Contact

defiarmor.io

### Project URL

defiarmor.io

### Github / Dev Docs

https://github.com/Eulith/armor-cli

### Twitter

eulith

### Primary integration

Core SDK, Safe Contracts

### Packages

Safe Core SDK

### Networks

Base, Ethereum, BNB, Polygon, Optimism, Avalanche, Arbitrum

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

No

**Comment by ennisjo** [comment]
@luca590 - Could you change the Project Scope from "Safe Apps" to "Safe Interface"? Safe Apps reflects to the Safe Apps sdk integration, whereas a "Safe Interface" reflects a deeper integration with Safe Core!

We'll add you in after.

```
Please provide the project scope.
Safe Apps
```

**Comment by debbchiasafe** [comment]
Have changed Project Scope to Safe Interface and added to the ecosystem db.
