### ISSUE TITLE
Update information for Nest Wallet

### ISSUE THREAD

**Issue by imysun** [safe-global/safe-ecosystem-database#39]
### Project

Nest Wallet

### Description

Nest Wallet is building a browser extension and mobile app dedicated to Safe Wallets. 

### Please provide the project scope.

Interface

### Select a primary category of your project.

Infrastructure

### Select secondary categories of your project.

Tooling, Wallet, Mobile App

### Project logo

![NestWallet_bird_nest](https://github.com/safe-global/safe-ecosystem-database/assets/61096824/005c92a8-e58f-4c40-87f7-df801d8acd47)

### Value proposition

Elevate your crypto experience with Nest Wallet!

- Our extension allows users to interact with any dApp, without custom integrations or third-party connections like WalletConnect. 
- Our mobile app enables biometric signing, making Safe easy and secure to use.

### Contact

contact@nestwallet.xyz

### Project URL

https://nestwallet.xyz/

### Github / Dev Docs

https://nest-wallet.gitbook.io/nest-wallet-help-center

### Twitter

https://twitter.com/nestwalletxyz

### Primary integration

Core SDK, Transaction Service API, Safe Contracts

### Networks

Base, Ethereum, BNB, Gnosis Chain, Polygon, Optimism, Avalanche, Arbitrum

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

Yes

**Comment by ennisjo** [comment]
LGTM - @germartinez

**Comment by debbchiasafe** [comment]
Updated internal db

**Comment by imysun** [comment]
@debbchiasafe

We would like to update our logo in the DB to the following:
![logo](https://github.com/safe-global/safe-ecosystem-database/assets/61096824/4dda88ea-1c41-4add-abe1-47da0f59d8c7)

**Comment by debbchiasafe** [comment]
Thanks @imysun this will be changed in our next update
