### ISSUE TITLE
Suggest a Project - BasedApp

### ISSUE THREAD

**Issue by edison0xyz** [safe-global/safe-ecosystem-database#40]
### Project

BasedApp

### Description

BasedApp is a Web 3.0 neobank that allows people to save and spend from their wallets. BasedApp issues a Visa debit card that taps onto funds held in Safe wallets for spending in real-life. BasedApp is connected to various DeFi protocols like Uniswap and Compound, and users can trade and invest on-the-go. 

### Please provide the project scope.

Core SDK Integration

### Select a primary category of your project.

Payments

### Select secondary categories of your project.

DeFi, Stablecoin, Wallet

### Project logo

<img width="1418" alt="Basedapp-icon-orange-2x" src="https://github.com/safe-global/safe-ecosystem-database/assets/6057323/2d8a0748-9478-4e3f-9132-f56a024e682d">

### Value proposition

BasedApp allows people to spend stablecoins directly from their wallet that is self-custodial. This is different than most crypto debit cards in the market out there. We utilize Account Abstraction to make the UI more seamless and friendly to other people.

### Contact

edison@basedapp.io

### Project URL

BasedApp

### Github / Dev Docs

https://github.com/suberra

### Twitter

https://twitter.com/BasedAppHQ

### Primary integration

Core SDK

### Packages

Safe Core SDK

### Smart Accounts

* 1-click invest features via batched transactions
* Social logins via Google, Email, etc.

### Networks

Polygon

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

None

**Comment by ennisjo** [comment]
LGTM

@germartinez can we please add this in the next db sync?

**Comment by debbchiasafe** [comment]
BasedApp has been added to the ecosystem db, new description will be updated in the next sync.
