### ISSUE TITLE
Lucidity Finance

### ISSUE THREAD

**Issue by ashwinYardi** [safe-global/safe-ecosystem-database#41]
### Project

Lucidity Finance

### Description

Lucidity Finance aggregates lending protocols across chains in order to unify the fragmented liquidity and improve capital efficiency for lenders and borrowers. Its in-house recommendation engine ensures that lenders and borrowers can access the best opportunities, and the protocol includes automation recipes like auto-refinance and liquidation prevention. In addition, users can use Lucidity to discover, originate, and manage their positions across the lending protocols.

In a nutshell, Lucidity is a leveraged liquidity layer for the DeFi Stack.

### Please provide the project scope.

Module

### Select a primary category of your project.

DeFi

### Select secondary categories of your project.

DeFi, SAFE, Lending / Borrowing, Institutional, Aggregator, Automation

### Project logo

![Logo_Black](https://github.com/safe-global/safe-ecosystem-database/assets/43699109/e209ba3f-4d23-4842-aea5-bdcf843d4856)
![Logomark_Black](https://github.com/safe-global/safe-ecosystem-database/assets/43699109/da1e4591-9c29-4f87-9722-1fdeee0ac782)

### Contact

https://t.me/LucidityFinance

### Project URL

https://lucidity.finance/

### Twitter

https://twitter.com/LucidityFinance

### Primary integration

Safe Contracts

### Packages

Safe Core SDK

### Modules / Guards

We have developed our own Module for a Safe. The module features functionalities like Batch Exec transactions, facilitate flashloans, security checks. Also will be extended to manage cross-chain communication between the safes for smooth multichain experience.

### Networks

Ethereum

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

No

**Comment by zzuziak** [comment]
Added to Notion, waiting for ecosystem website sync 🙏
