### ISSUE TITLE
Suggest a project - Cometh Connect

### ISSUE THREAD

**Issue by romemore** [safe-global/safe-ecosystem-database#44]
### Project

Cometh Connect ☄️

### Description

Cometh Connect is an SDK (Web & Unity) that enables applications to provide to their users a smart wallet (Safe) controlled with a biometric signer (passkey).

### Please provide the project scope.

Core SDK Integration

### Select a primary category of your project.

Collectibles / NFT

### Select secondary categories of your project.

Wallet

### Project logo

![Union](https://github.com/safe-global/safe-ecosystem-database/assets/827536/4cb19dc4-73cc-49d0-8aac-b0bf5c703668)

### Value proposition

Easy onboarding for web 2 users with only one biometry to get a Safe smart wallet.
**Web 2 convenience** with biometry & recovery, user has the same experience than services he uses daily
**Truely non custodial** signer key is managed by the device crypto hardware
**Based on proved standards** WebAuthn + Safe wallet

### Project URL

https://cometh.io

### Github / Dev Docs

https://docs.cometh.io

### Twitter

cometh

### Primary integration

Core SDK

### Packages

Safe Core SDK

### Smart Accounts

Cometh Connect leverages Smart Accounts to : 

- use multiple devices as signers for the same account, 
- add recovery feature,
- verify transaction signature type not handled by the chain, 
- enable gasless transactions to specific contracts.

### Networks

Base, Ethereum, BNB, Gnosis Chain, Polygon, Optimism, Avalanche, Arbitrum, Aurora, Celo

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

Yes

**Comment by ennisjo** [comment]
@DiogoSoaress @debbchiasafe LGTM - can we push this to the next update?
