### ISSUE TITLE
Business account request

### ISSUE THREAD

**Issue by rossneilson** [safe-global/safe-ecosystem-database#45]
Hi, I submitted a request previously after chatting to support and after following up was directed to making an issue here. 
We have a safe we have been using for our startup with significant funding and grants in it. We just incorporated in the EU and were wanting to find out if we could have some business account to continue using our safe for transactions which would be seen as transactions for our business. Is this possible?
Would really love to keep using safe instead of moving all our funds to a business account on a CEX

**Comment by debbchiasafe** [comment]
Hi @rossneilson this is not really the right channel for such a request, but you can go to https://safe.global/ecosystem and filter the category by "Accounting" to check out some partner projects that might be what you are looking for.
