### ISSUE TITLE
Add ZenGuard to ecosystem hub

### ISSUE THREAD

**Issue by adam-hurwitz** [safe-global/safe-ecosystem-database#51]
### Project

ZenGuard

### Description

Safe account creation with social logins and new features for existing Safe accounts and developers.

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

Infrastructure

### Select secondary categories of your project.

SAFE, Infrastructure, Wallet

### Project logo

![zenguard](https://github.com/safe-global/safe-ecosystem-database/assets/3938076/76dbfb8a-cca1-4faa-ab26-37466b4c9b92)

### Project URL

zenguard.xyz

### Github / Dev Docs

https://docs.zenguard.xyz

### Twitter

https://twitter.com/zenguardxyz

### Primary integration

Unsure

### Packages

Unsure

### Networks

Base, Ethereum, BNB, Gnosis Chain, Polygon, Optimism

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

Yes

**Comment by debbchiasafe** [comment]
Hi @adam-hurwitz will need the primary integration field to update the database.

**Comment by debbchiasafe** [comment]
Updated!

**Comment by debbchiasafe** [comment]
Thanks for the catch Adam! Will be patched in the next sync
