### ISSUE TITLE
Headquarters (HQ.xyz)

### ISSUE THREAD

**Issue by alexteohq** [safe-global/safe-ecosystem-database#58]
### Project

Headquarters (HQ.xyz)

### Description

The Finance Back-office for Web3 builders and funds. Payments and accounting of on-chain activities made simply - all from one dashboard.

### Please provide the project scope.

Interface

### Select a primary category of your project.

DAO Tooling

### Select secondary categories of your project.

Dashboard, Accounting, Payments

### Project logo

![HQlogo- 1080x1080px](https://github.com/safe-global/safe-ecosystem-database/assets/123946590/b8a9154c-f63d-47b6-94f1-52b75918bd1a)

### Value proposition

Headquarters (HQ.xyz): Empowering crypto teams with seamless financial management. Our platform ensures an organised and compliant financial back-office, enabling teams to streamline bookkeeping and business payments. Level up your Treasury Ops with Headquarters.

### Contact

alex@hq.xyz

### Project URL

https://hq.xyz

### Github / Dev Docs

https://github.com/hqxyz

### Twitter

https://twitter.com/HQ_xyz

### Primary integration

Safe Apps SDK

### Packages

Safe Core SDK, Safe Service Client, Safe Ethers Lib, web3-react

### Modules / Guards

NA (if this is in respect to specific web3 security library / services)

### Smart Accounts

We believe that Smart Accounts will enable web3 users to benefit from improved security, as well as have a better UX for their financial operations.

Currently, we have built a product that allows Safe users to import their Safes and seamlessly approve / reject / execute transactions. Over time, we we will begin to integrate fuller features utilizing the Core SDK integration, enabling the user to have access to other Safe features.

### Networks

Ethereum, BNB, Polygon, Arbitrum

### Can you create a Safe via the interface?

No

### Can you import an existing Safe via the interface?

Yes

**Comment by debbchiasafe** [comment]
Thanks @alexteohq this will be added during our next sync

**Comment by alexteohq** [comment]
thanks @debbchiasafe

**Comment by alexteohq** [comment]
Hi @debbchiasafe wanted to check if you might need any extra details to help with this?

Just to share that many of our top users are connecting their Safes to HQ & making payouts using their Safes.

**Comment by debbchiasafe** [comment]
Hey @alexteohq sorry for the delay on this. It's in the queue pending deployment.
