### ISSUE TITLE
Suggest a project

### ISSUE THREAD

**Issue by graadient** [safe-global/safe-ecosystem-database#59]
### Project

Zeal Wallet

### Description

DeFi Wallet with free bank transfers and complete portfolio. Biometrics and simulations keep you Safe!

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

DeFi

### Select secondary categories of your project.

Wallet

### Project logo

![teal bg Zeal](https://github.com/safe-global/safe-ecosystem-database/assets/18259639/dfee75ff-6d81-4ae7-960a-254b8dcbe1f7)

### Value proposition

Create a wallet with the touch of a finger, top it up for free, and make transactions without gas worries — all within minutes. A Smart Wallet built with Safe, that’s protected with Biometrics and passkeys. The future of wallets is now.

### Contact

@graadient

### Project URL

https://www.zeal.app/

### Github / Dev Docs

https://github.com/zealwallet/Wallet

### Twitter

https://twitter.com/zealwallet

### Primary integration

Safe Contracts

### Packages

Transaction Service API, Safe Deployments

### Networks

Base, Ethereum, BNB, Gnosis Chain, Polygon, Optimism, Avalanche, Arbitrum, Aurora, Celo

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

Yes

**Comment by debbchiasafe** [comment]
Thanks @graadient have changed the project scope to "Interface" (Safe Apps is for apps integrated within Safe{Wallet} UI), and will be added during the next sync.

**Comment by zzuziak** [comment]
Added! Sorry for a huge delay here 🙏
