### ISSUE TITLE
Suggest a project (Acctual)

### ISSUE THREAD

**Issue by IssaMohamudHassan** [safe-global/safe-ecosystem-database#60]
### Project

Acctual

### Description

Acctual is accounts payable (AP) and accounts receivable (AR) automation for crypto and fiat. Synced to your accounting system.

### Please provide the project scope.

Core SDK Integration

### Select a primary category of your project.

Payments

### Select secondary categories of your project.

Accounting, Payments

### Project logo

![acctual_logo](https://github.com/safe-global/safe-ecosystem-database/assets/113362272/c933fd9d-0ad4-47c3-9938-4bb929f8072f)

### Value proposition

Acctual is the first true accounts payable and receivables platform for crypto. We make it easy for businesses to pay bills through their Safe. All bills and invoices are synced to the general ledger (Quickbooks, Xero, etc.) and contacts are mapped to their wallet addresses. Acctual is currently developing a fiat integration with plans to have an all encompassing platform to manage your financial operations.

### Contact

issa@acctual.com

### Project URL

https://acctual.com/

### Twitter

@acctualteam

### Primary integration

Core SDK

### Packages

Safe Core SDK, Transaction Service API

### Modules / Guards

We have only used the Safe protocol kit sdk and transaction service API.

### Smart Accounts

The Acctual accounts payable solution takes advantage of the multi-signature scheme and transaction batching. We allow companies to import their bills, leverage the Safe signatures mechanism for approval workflows, and finally execute a number of bill payments in a single batch transaction.

### Networks

Ethereum, Polygon, Optimism, Arbitrum

### Can you create a Safe via the interface?

No

### Can you import an existing Safe via the interface?

Yes

**Comment by debbchiasafe** [comment]
Thanks @IssaMohamudHassan, this will be added to our next db sync

**Comment by IssaMohamudHassan** [comment]
> Thanks @IssaMohamudHassan, this will be added to our next db sync

Hey @debbchiasafe, just wanted to check in here!

**Comment by zzuziak** [comment]
Hey @IssaMohamudHassan - Acctual is now listed on our Ecosystem page:

<img width="1011" alt="image" src="https://github.com/safe-global/safe-ecosystem-database/assets/39556343/6851f9c1-a79b-4ce0-a097-98b1e9a9f6b5">
