### ISSUE TITLE
Suggest a project - Eulith

### ISSUE THREAD

**Issue by luca590** [safe-global/safe-ecosystem-database#61]
### Project

Eulith

### Description

Eulith provides asset managers and accredited investors with the best technology and financial services to access & manage capital on-chain.

### Please provide the project scope.

Core SDK Integration

### Select a primary category of your project.

DeFi

### Select secondary categories of your project.

Institutional, Yield, Automation

### Project logo

![EULITH - logo_CMYK_BGWhite_PNG](https://github.com/safe-global/safe-ecosystem-database/assets/4744524/50f117ed-5e04-4c9c-bb98-582a32452bd8)

### Value proposition

DeFi Armor is the most secure way to trade and run automated strategies on-chain. Poems is the first DeFi native Position Order Execution and Management System ("POEMS").

### Contact

lucas@eulith.com

### Project URL

eulith.com

### Github / Dev Docs

https://github.com/Eulith

### Twitter

lucas_tweeting

### Primary integration

Safe Contracts

### Packages

Safe Deployments

### Modules / Guards

Currently non, but we will probably upgrade to use a guard later

### Smart Accounts

At the moment, we have our own Safe module which enables us to separate trading and withdrawal keys.

### Networks

Base, Ethereum, BNB, Polygon, Optimism, Avalanche, Arbitrum, Celo

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

Yes

**Comment by luca590** [comment]
![EULITH---logo_CMYK_BG_Blue_PNG](https://github.com/safe-global/safe-ecosystem-database/assets/4744524/de182d17-8a32-459a-8da3-7f1e782fa764)

Here's also a white version of our logo if this is more helpful

**Comment by debbchiasafe** [comment]
Thanks @luca590 this will be added to our next db sync

**Comment by zzuziak** [comment]
@debbchiasafe added to Notion DB 👌
