### ISSUE TITLE
Suggest a project - Mest

### ISSUE THREAD

**Issue by imweihuang** [safe-global/safe-ecosystem-database#64]
### Project

Mest

### Description

Mest is an open, user-friendly platform for sharing and labeling blockchain transactions and wallet collections. It aims to enrich the blockchain community by allowing users to contribute content that serves the public good. Mest aspires to be a central hub for valuable blockchain insights and a collective effort to navigate the blockchain landscape.

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

DAO Tooling

### Select secondary categories of your project.

Tooling

### Project logo

![MestLogo](https://github.com/safe-global/safe-ecosystem-database/assets/24487707/23ee035b-2e2c-4110-938a-a339427ac2aa)

### Value proposition

Mest's value proposition for Safe revolves around enhancing the visibility and understanding of transactions performed through Gnosis Safe. The core issue addressed by Mest is the difficulty in understanding transaction details due to the way Gnosis Safe executes transactions, often making it hard to discern the actual actions taken and the asset changes involved.

Mest offers a solution by parsing the execTransaction method calls within Gnosis Safe contracts to extract actionable data, counterparties, and even signer information from signatures. This allows for a deeper analysis and transformation of transaction data into human-readable forms, covering a wide range of scenarios like DEX swaps, NFT trades, bridging, lending, and more. Unlike other platforms that may not correctly interpret Safe transactions, leading to a lack of clarity on what was done and which assets were affected, Mest aims to provide a comprehensive breakdown.

Key improvements Mest brings to the table include:

- The ability to understand who the counterparties in a transaction are, even when they are Gnosis Safe wallets.
- Enhanced readability by parsing and displaying the actual method called instead of a generic execTransaction.
- Deeper transaction analysis that covers various scenarios beyond basic transfers, such as trades, liquidity actions, and more.
- Richer counterparty metadata, including logos and identities, to better understand transaction contexts.
- Accurate asset change analysis, as opposed to missing or incorrect information on other platforms.

### Contact

lucas@mest.io

### Project URL

https://mest.io/

### Github / Dev Docs

https://github.com/mest-io

### Twitter

mest_io

### Primary integration

Safe Apps SDK

### Packages

Safe Core SDK

### Networks

Base, Ethereum, BNB, Gnosis Chain, Polygon, Optimism, Avalanche, Arbitrum, Aurora

### Can you create a Safe via the interface?

No

### Can you import an existing Safe via the interface?

No

**Comment by zzuziak** [comment]
Will be included in the next db sync 👌  @imweihuang is Safe the only Smart Account provider you're integrating, or do you also integrate with other providers?

**Comment by zzuziak** [comment]
@imweihuang could you also provide a white logo, as this one will not be visible on our Ecosystem page?
