### ISSUE TITLE
Suggest a project

### ISSUE THREAD

**Issue by JJ-Mural** [safe-global/safe-ecosystem-database#66]
### Project

Mural

### Description

Instant Global Payments and Invoicing. Eliminate delays and fees with Mural.

### Please provide the project scope.

Interface

### Select a primary category of your project.

Payments

### Select secondary categories of your project.

Institutional, Stablecoin, Accounting

### Project logo

![Symbol-dark over light](https://github.com/safe-global/safe-ecosystem-database/assets/139145457/a6dc7dde-5d33-43de-939e-cf3c524e883e)

### Value proposition

Move beyond slow international wires, costly transaction fees, and lack of transaction visibility with Mural.  More than just a payment method, Mural is designed to empower your business with an all-in-one platform combining global payments, automated invoicing, flexible account payable flows, and the latest in blockchain technology. Our mission is to make every international transaction fast, scalable, and secure.

### Contact

support@muralpay.com

### Project URL

https://www.muralpay.com/

### Twitter

mural_pay

### Primary integration

Core SDK

### Packages

Safe Core SDK, Transaction Service API, Safe Deployments, Safe Ethers Lib

### Smart Accounts

Mural uses Safe Smart Accounts for core asset account infrastructure on its payments and invoicing platform. Customers benefit from customizable approval policies and flexible signers for payments / transfers

### Networks

Ethereum, Polygon, Optimism, Avalanche, Arbitrum, Celo

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

Yes

**Comment by JJ-Mural** [comment]
Please help us remove or update the current Mural app listed in the Ecosystem page https://safe.global/ecosystem?page=2
Thank you!

**Comment by zzuziak** [comment]
Added 👌
