### ISSUE TITLE
Suggest a project

### ISSUE THREAD

**Issue by purybr365** [safe-global/safe-ecosystem-database#67]
### Project

Picnic

### Description

Picnic is creating a new consumer DeFi category, providing access to crypto in the right way to anyone.

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

DeFi

### Select secondary categories of your project.

Payments, Yield, Wallet

### Project logo

![logo-green](https://github.com/safe-global/safe-ecosystem-database/assets/97474079/717a2a45-6679-49be-b1e5-490482cc7c75)

### Value proposition

Picnic connects anyone directly to the blockchain, without intermediaries. We facilitate wallet creation with social login, abstract gas via ERC-4337, facilitates swap operations and yield generating strategies. Everything in a language that anyone can understand and use.

### Contact

hi@usepicnic.com

### Project URL

https://usepicnic.com

### Github / Dev Docs

https://github.com/usePicnic

### Twitter

https://x.com/usePicnic

### Primary integration

Safe Contracts

### Modules / Guards

Safe 4337

### Networks

Polygon

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

No

**Comment by zzuziak** [comment]
Thank you @purybr365! @debbchiasafe fyi - already moved to Notion
