### ISSUE TITLE
Epoch Protocol

### ISSUE THREAD

**Issue by Man-Jain** [safe-global/safe-ecosystem-database#68]
### Project

Epoch Protocol

### Description

The Infrastructure Layer for Autonomous Web3.

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

Infrastructure

### Select secondary categories of your project.

DeFi, SAFE, Tooling, Infrastructure, Automation

### Project logo

![epoch500x500](https://github.com/safe-global/safe-ecosystem-database/assets/12700384/7461fcd0-abba-46db-96c7-fa52174e6b21)

### Value proposition

At Epoch Protocol, we're building the infrastructure middleware for intent solvers, AI Agents and protocols to constantly monitor the intent conditions and automate user intents.

### Contact

to.epochprotocol@gmail.com

### Project URL

https://www.epochprotocol.xyz

### Github / Dev Docs

https://docs.epochprotocol.xyz

### Twitter

https://twitter.com/0xepochprotocol

### Primary integration

Core SDK, Safe Contracts

### Packages

Safe Core SDK, Safe Deployments, web3-onboard, web3-react, safe-apps-wagmi, safe-apps-web3modal

### Modules / Guards

SAFE ERC4337 Module,
Epoch Module

### Smart Accounts

Epoch Protocol utilizes Account Abstraction and Smart Wallets as a core component of our architecture, with a custom module on top of the Smart Wallets to enable automation. 

Smart Wallets with their amazingly flexible signature mechanisms allow us to keep user's intent, monitor the conditions of those intents and after verification execute them onchain. All while still keeping the funds SAFE.

Being modular and expandable, Smart Wallets also allow us to expand their capabilities in future if and when needed. 

### Networks

Ethereum, Polygon, Optimism

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

Yes

**Comment by zzuziak** [comment]
@debbchiasafe transferred to Notion 👌
