### ISSUE TITLE
Suggest a project

### ISSUE THREAD

**Issue by justinridgely** [safe-global/safe-ecosystem-database#69]
### Project

Syndicate

### Description

Transaction APIs and L3 rollups to to power onchain applications.

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

Infrastructure

### Select secondary categories of your project.

Tooling, Infrastructure, Gaming

### Project logo

![Syndicate-Primary-LogoBlack-On-Transparent](https://github.com/safe-global/safe-ecosystem-database/assets/24594205/51f2e8ac-97ae-449d-9b5c-d65fa9eeaa82)
![Syndicate-Primary-Logo-White-On-Transparent](https://github.com/safe-global/safe-ecosystem-database/assets/24594205/98f811ff-418c-4cf7-bb75-6a52540ecbd7)

### Value proposition

Our modular end-to-end infrastructure abstracts the complexity of sending onchain transactions and decreases development time — making it easier, cheaper and faster for developers to build, launch and grow onchain products at any scale.

### Contact

justin@syndicate.io

### Project URL

https://syndicate.io

### Github / Dev Docs

https://docs.syndicate.io

### Twitter

https://twitter.com/syndicateio

### Networks

Base, Ethereum, BNB, Gnosis Chain, Polygon, Optimism, Arbitrum

### Can you create a Safe via the interface?

No

### Can you import an existing Safe via the interface?

No

**Comment by zzuziak** [comment]
Transferred to Notion @debbchiasafe 👍
