### ISSUE TITLE
FailSafe

### ISSUE THREAD

**Issue by aamirethlas** [safe-global/safe-ecosystem-database#70]
### Project

FailSafe

### Description

FailSafe became generally available in September of 2023. It is part of the overall defense-in-depth product lineup originally envisioned in our [whitepaper](https://arxiv.org/abs/2304.03387). FailSafe is designed to deal with what to date has been regarded as game-over scenarios: an attacker learns the victim wallet's private key or seed phrase, or gains an unlimited token allowance via phishing or smart contract compromise. On enrollment of an Externally Owned Address (EOA) or a wallet contract (i.e., Gnosis Safe), the FailSafe Interceptor service monitors globally pending transactions across public, private, and internal transaction streams. Once an attacker's pending transaction is detected, FailSafe submits a just-in-time counter transaction that moves the protected wallet's assets to a recovery vault before the attacker's transaction is executed. This interception is triggered via safe mode (the equivalent of a virtual transaction lock) or smart mode, which uses threat intel to intercept only if the transaction counterparty is flagged as fraudulent.

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

Infrastructure

### Select secondary categories of your project.

Infrastructure

### Project logo

![failsafe_logo_square](https://github.com/safe-global/safe-ecosystem-database/assets/111723932/91e1b7c7-bbbf-4a8e-addd-fbba466f5a57)

### Value proposition

People who use Safe could face big risks if someone discovers their owner's private keys or tricks them into giving access to their wallets. These risks can lead to losing all their money in the wallet, which can be really bad.

FailSafe works with Gnosis Safe to add an extra layer of protection. It keeps an eye on all transactions that try to move money out of the wallet. If it sees something suspicious, it steps in quickly to move the money to a safe place.

### Contact

aamir@ethlas.com

### Project URL

https://app.getfailsafe.com/

### Github / Dev Docs

https://doc.getfailsafe.com/

### Twitter

https://twitter.com/protectmywallet

### Primary integration

Safe Apps SDK

### Packages

safe-apps-wagmi

### Networks

Ethereum, BNB, Polygon

### Can you create a Safe via the interface?

No

### Can you import an existing Safe via the interface?

Yes

**Comment by zzuziak** [comment]
Will be included in the next DB sync 👌

**Comment by zzuziak** [comment]
Added 👌
