### ISSUE TITLE
Add support for Tangle EVM

### ISSUE THREAD

**Issue by drewstone** [safe-global/safe-ecosystem-database#71]
### Project

Tangle

### Description

Tangle is an MPC-as-a-service restaking network for distributing complex offchain compute ranging from cryptographic applications, to AI applications, to other cloud compute. It is EVM compatible, aggregating liquidity from any ecosystem to secure the services run by Tangle network validators.

### Please provide the project scope.

Network

### Select a primary category of your project.

Infrastructure

### Select secondary categories of your project.

Marketplace

### Project logo

![image](https://github.com/safe-global/safe-ecosystem-database/assets/13153687/af2d9b39-640f-4985-a828-04dc8f807969)

### Value proposition

Tangle's value prop centers around outsourcing complex computational tasks to a network of validators who restake assets to provide complex and cryptographically secure services. The infrastructure allows developers to request complex computations and receive these outputs on any chain without needing to build the infrastructure themselves.

### Contact

drew@tangle.tools

### Project URL

https://tangle.tools

### Github / Dev Docs

https://github.com/webb-tools/tangle

### Twitter

https://twitter.com/tangle_network

### Primary integration

Safe Apps SDK, Core SDK, Transaction Service API, Unsure, Safe Contracts

### Packages

Unsure

### Modules / Guards

We are looking to integrate with Safe services and add support for Tangle in the Safe Wallet Desktop App (and mobile if possible).

### Smart Accounts

Our infrastructure allows any EVM account to create access control mechanisms over their offchain services. Having SAFE Smart Accounts on our chain will allow an even more streamlined experience for developers looking to distribute the trust of executing their services using SAFE accounts.

### Can you create a Safe via the interface?

None

### Can you import an existing Safe via the interface?

None

**Comment by zzuziak** [comment]
Closing this issue as team has reached out directly via email.
