### ISSUE TITLE
Suggest a project

### ISSUE THREAD

**Issue by lpvelo** [safe-global/safe-ecosystem-database#72]
### Project

BIM Finance

### Description

More Than An Exchange, buy, swap, bridge and stake your cryptocurrencies from a single interface.

### Please provide the project scope.

Connection provider

### Select a primary category of your project.

DeFi

### Select secondary categories of your project.

DeFi, Bridge, Staking

### Project logo

https://bim.finance/asset/logos/bim_icon_logo.png

### Value proposition

Why BIM Protocol?
BIM Protocol has been audited and secured. The protocol is completely open source, which allows anyone to interact with a user interface client, API or directly with the smart contracts on the Polygon network and other EVM blockchain. Being open source means that you are able to build any third-party service or application to interact with the protocol and enrich your product.

How do I use the BIM protocol?
How to use the BIM protocol? To Buy Sell, Bridge, Provide Liquidity, Swap Tokens, or Vote on Governance Proposals, go to the [BIM Exchange](https://exchange.bim.finance/) interface and connect a Web3 wallet.

### Contact

contact@bim.finance

### Project URL

https://bim.finance/

### Github / Dev Docs

https://docs.bim.finance/faq

### Twitter

https://twitter.com/BIM_Finance

### Primary integration

Safe Apps SDK

### Packages

Safe Service Client

### Modules / Guards

Liquidity provider : Uniswap / Connext / Beefy 
Audit : Cyberscope Coinscope Certik 

### Smart Accounts

To carry out transactions on our platform. Swap Bridge stack 

### Networks

Base, Ethereum, BNB, Gnosis Chain, Polygon, Optimism, Avalanche, Arbitrum

### Can you create a Safe via the interface?

No

### Can you import an existing Safe via the interface?

Yes

**Comment by zzuziak** [comment]
Hi @lpvelo, thank you for submitting the request. I've noticed you selected the Safe Apps SDK as the primary integration, but I suppose you meant the Core SDK as you're rather using our Safe Service Client? 🤔

**Comment by lpvelo** [comment]
Hello,

Yes, we use safe for our DAO. As well as for our protocol fees and we allow
people to make transactions on our platforms with a safe wallet.

Sincerely




*Léo PESTRE*
*CEO (**CHIEF EXECUTIVE OFFICER**)*
*M:* +33 6 31 01 68 95
*E:* ***@***.***


bim.finance
exchange.bim.finance

**Comment by zzuziak** [comment]
Added 👌
