### ISSUE TITLE
Alloc8_Safe_Ecosystem

### ISSUE THREAD

**Issue by devsxtra2** [safe-global/safe-ecosystem-database#74]
### Project

Alloc8

### Description

Alloc8 enables users to allocate tokens to Strategy Vaults to maximize point & yield farming across all chains.

### Please provide the project scope.

Interface

### Select a primary category of your project.

DeFi

### Select secondary categories of your project.

DeFi, Lending / Borrowing, Yield, Automation

### Project logo

![logo main](https://github.com/safe-global/safe-ecosystem-database/assets/111141526/475d152e-c8ef-4791-9594-e8afe0f1a67a)
![only 8](https://github.com/safe-global/safe-ecosystem-database/assets/111141526/d2e3e0e0-a5ff-4115-82d2-a7bbf57af2b3)

### Contact

ayush@alloc8.xyz

### Twitter

https://twitter.com/alloc8_xyz

### Primary integration

Core SDK, Transaction Service API, Safe Contracts

### Packages

Safe Core SDK, Transaction Service API, Safe Deployments, Safe Ethers Adapter, web3-react, safe-apps-wagmi, safe-apps-web3modal

### Modules / Guards

Created our own modules for the liquidation of funds on the sub-account using Gelato as the caller.

### Smart Accounts

Using the security and safety of Safe, for every new user on Alloc8, a new Safe smart account is deployed to be used as a sub-account. Users use the Safe-powered smart sub-accounts to leverage borrow and interact with the whitelisted protocols on Alloc8.

### Networks

Ethereum, Gnosis Chain, Arbitrum

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

Yes

**Comment by zzuziak** [comment]
Thanks @devsxtra2 🙏
