### ISSUE TITLE
LexDAO | Accounting Infrastructure and Financial Management - 1155 Integration

### ISSUE THREAD

**Issue by cimplylimited** [safe-global/safe-ecosystem-database#77]
### Project

LexDAO Accounting Infrastructure

### Description

We're building out our financial management processes in LexDAO and would like SAFE to be part of that dialogue.

### Please provide the project scope.

Network

### Select a primary category of your project.

DAO Tooling

### Select secondary categories of your project.

Dashboard, DAO Tooling, Accounting, Payments, Tooling, Bridge, Infrastructure, Staking, Donation, Automation, Wallet, Messaging, Privacy

### Project logo

![LexDAO Logo File (004)](https://github.com/safe-global/safe-ecosystem-database/assets/106759485/f2468709-1867-428f-acb7-0a7e8db569c0)

### Value proposition

As the premier Legal Engineering Guild, LexDAO has a history of using SAFE.  With a reinvigorated membership base, we are looking to get more involved in projects we believe have a foundational future in the web3 ecosystem.  As we mature, LexDAO is working on building out its financial management tooling and connecting it with network infrastructure through 1155 tokens, 4337, and 6551 standards.  Safe has historically been ahead of the curve, but there are elements of the application that would significantly improve user experience and adoption.  This app is an organizational onramp and should be at the center of the conversation around fiduciary responsibility.  We are mapping a network of wallets that fosters a progressive decentralization and want to collaborate further with SAFE.  If you have any interest in discussing further please reach out.

### Contact

assistantoperator@lexdao.org

### Project URL

https://lexdao.org

### Github / Dev Docs

https://github.com/lexDAO

### Twitter

https://twitter.com/lex_DAO

### Primary integration

Unsure

### Packages

Unsure, Safe Deployments

### Modules / Guards

eth:0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4

### Smart Accounts

Don't think so

### Is Safe the only Smart Account provider you are using in your project?

Yes

### Networks

Arbitrum, Avalanche, Ethereum, Gnosis Chain, Optimism, Polygon PoS, Polygon zkEVM

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

No

**Comment by cimplylimited** [comment]
## Product Feedback Item 1
As per one of our members, we are working with a layer 2 that our safe was spun up against (Optimism).  What we've noticed as we are trying to purchase through your wallet connect dApp connector is that because the asset we are purchasing (NFT on OpenSea) is on Mainnet, the swap mechanism necessary to take wrapped ETH on Optimism and make purchase on main net through integration is a fragmented workflow.  As you start getting more and more L2s etc, this will be increasingly more difficult to manage.  There are a few technical solutions such as temporary storage implementations etc. we would like to discuss with you.

**Comment by zzuziak** [comment]
Hey @cimplylimited, I'll close the issue for now as this database is meant for projects with existing integrations. Let's connect directly in the meantime to discuss your idea. I'll reach out via email!
