### ISSUE TITLE
Update Multisight

### ISSUE THREAD

**Issue by bartosjiri** [safe-global/safe-ecosystem-database#79]
Would like to request an update of the Multisight project information. Fields to be updated:
- Project logo: [Link](https://multisight.app/meta/logo-symbol.svg)
- Description: Multisight is a knowledge and tooling platform dedicated to improving the access to and distribution of information about multisigs
- Twitter URL: https://twitter.com/multisightapp
- Github URL: https://github.com/multisightapp
- Networks: All networks with available Transaction Service API listed in [Safe API docs](https://docs.safe.global/core-api/transaction-service-supported-networks).

Thank you in advance!

**Comment by zzuziak** [comment]
Thanks @bartosjiri! Will be included in the next update 👌

**Comment by zzuziak** [comment]
Updated 👌
