### ISSUE TITLE
Add new tags for Superfluid

### ISSUE THREAD

**Issue by vmichalik** [safe-global/safe-ecosystem-database#8]
<img width="193" alt="image" src="https://github.com/safe-global/safe-ecosystem-database/assets/12459761/8f2cde3e-5099-4620-8053-4ae357770c0b">

I'd like to request these categories are added to Superfluid as well: DeFi, Automation, Infra
Let me know if there's anything else need to be done on our side!

**Comment by germartinez** [comment]
@ennisjo this is how Superfluid categories currently look like.
Let me know where the new ones should be added.
```
"primary_category": "DAO Tooling",
"secondary_categories": "Accounting, Payments",
```

**Comment by vmichalik** [comment]
Hello, can we make the primary "Payments" and secondary all others?
Thanks!

**Comment by ennisjo** [comment]
Let's do it! cc @germartinez can we proceed with a review?
