### ISSUE TITLE
Suggest a project

### ISSUE THREAD

**Issue by jamesmccomish** [safe-global/safe-ecosystem-database#80]
### Project

Onit

### Description

Onit lets you manage your Safe from an XMTP group chat & onboard new users into passkey smart accounts

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

DAO Tooling

### Select secondary categories of your project.

Messaging

### Project logo

![Onit Avatar@2x](https://github.com/safe-global/safe-ecosystem-database/assets/68289880/00009e9a-1c05-4e7c-b7af-01c75efa8fca)

### Value proposition

- With Onit you can chat with your Safe and make/execute proposals directly from the conversation
- Natural language transaction building from chat messages make transaction building easy
- New users are onboarded into a passkey smart account

### Contact

james@forumdaos.com

### Project URL

https://onit.fun

### Github / Dev Docs

https://github.com/onit-labs/onit-contracts

### Twitter

https://twitter.com/onit_fun

### Primary integration

Safe Contracts

### Packages

Transaction Service API, Safe Deployments

### Smart Accounts

When a new user joins Onit or you invite someone without a wallet to your Safe, we create them a passkey controlled smart account. They can then act as a signer on your Safe, and have a wallet of their own to get started in crypto.

We will be building out modules for our accounts / Safes.

### Is Safe the only Smart Account provider you are using in your project?

Yes

### Networks

Base, Ethereum, Optimism

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

Yes

**Comment by zzuziak** [comment]
Will be included in the next sync 👌

**Comment by zzuziak** [comment]
Added! 👌
