### ISSUE TITLE
Update Fluidkey

### ISSUE THREAD

**Issue by mozrt2** [safe-global/safe-ecosystem-database#81]
### Project

Fluidkey

### Description

Fluidkey protects your privacy. Receive and manage funds onchain without publicly linking them to you.

### Please provide the project scope.

Interface

### Select a primary category of your project.

Payments

### Select secondary categories of your project.

Wallet, Privacy

### Project logo

![fluidkeyIcon-21 (1)](https://github.com/safe-global/safe-ecosystem-database/assets/79607357/0756b16c-7213-40f7-aea1-d3188e351493)

### Value proposition

Fluidkey gives users better privacy defaults on public EVM chains by allowing them to receive funds in a fresh address for every transaction.

### Contact

hey@fluidkey.com

### Project URL

fluidkey.com

### Github / Dev Docs

docs.fluidkey.com

### Twitter

fluidkey

### Primary integration

Safe Contracts

### Modules / Guards

N/A

### Smart Accounts

Every stealth account generated by Fluidkey is a Safe smart account.

### Is Safe the only Smart Account provider you are using in your project?

Yes

### Networks

Arbitrum, Base, Ethereum, Optimism, Polygon PoS

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

No

**Comment by zzuziak** [comment]
Will be included in the next sync 👌

**Comment by zzuziak** [comment]
Updated 👌
