### ISSUE TITLE
BlockPeer

### ISSUE THREAD

**Issue by taknev83** [safe-global/safe-ecosystem-database#83]
### Project

BlockPeer

### Description

An integrated digital asset and fiat accounting platform for institutions!

### Please provide the project scope.

Core SDK Integration

### Select a primary category of your project.

Payments

### Select secondary categories of your project.

Institutional, Accounting, Payments

### Project logo

![BlockPeer Logo](https://github.com/safe-global/safe-ecosystem-database/assets/61316462/3179f084-d0f8-439b-87ab-388a3bab5b7a)

### Value proposition

BlockPeer is a blockchain wallet integrated accounting platform. Safe multisig wallets are natively integrated into BlockPeer. Finance teams from web3 and web2 can seamlessly create and operate Safe multisig wallets from our integrated digital asset and fiat accounting platform. 

Coupled with in-built MPC wallets, BlockPeer just needs an email to create an EOA wallet and Safe multisig wallets. A simple login flow resembles a typical web2 accounting platform login process, a web2-like UI.

Safe multisig is deeply integrated into the Accounts Payable (AP) workflows in BlockPeer. Accounting context for signers to understand the underlying payment transaction and automatic accounting for bills paid through BlockPeer's Safe interface adds significant value to finance teams!

### Contact

venkatesh@blockpeer.finance

### Project URL

https://www.blockpeer.finance

### Twitter

https://x.com/blockpeerfin

### Primary integration

Core SDK

### Packages

Safe Core SDK, Transaction Service API, Safe Deployments

### Smart Accounts

Smart accounts eliminate the risk of EOA's single point of control/failure. With BlockPeer's integrated Safe Smart accounts, institutions can seamlessly manage digital asset payment flows among their team members right within our integrated accounting platform!

### Is Safe the only Smart Account provider you are using in your project?

Yes

### Networks

Arbitrum, Avalanche, Base, BNB, Ethereum, Gnosis Chain, Optimism, Polygon PoS, Polygon zkEVM

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

No

**Comment by zzuziak** [comment]
Will be included in our next sync 👌

**Comment by taknev83** [comment]
Thanks :blush:
