### ISSUE TITLE
Palmera

### ISSUE THREAD

**Issue by Mircala** [safe-global/safe-ecosystem-database#87]
### Project

Palmera

### Description

Smart Treasury Management: Multiple Safes, Multiple Chains, One Dashboard.

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

Payments

### Select secondary categories of your project.

Dashboard, DAO Tooling, Accounting, Aggregator

### Project logo

![Palmera Logo](https://github.com/safe-global/safe-ecosystem-database/assets/98910597/078f0a1c-45ff-4722-84fd-fb574e02952b)

### Value proposition

Palmera aggregates all your Safes across multiple chains to streamline your operations and treasury management, all from a single dashboard.

### Contact

general@palmeradao.xyz

### Project URL

https://www.palmeradao.xyz/

### Twitter

https://x.com/palmera_dao

### Primary integration

Core SDK, Transaction Service API, Safe Contracts

### Packages

Safe Core SDK, Safe Service Client, Transaction Service API, Safe Deployments, Safe Ethers Adapter, web3-onboard

### Is Safe the only Smart Account provider you are using in your project?

Yes

### Networks

Arbitrum, Base, Celo, Ethereum, Gnosis Chain, Optimism, Polygon PoS

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

Yes

**Comment by zzuziak** [comment]
Noted, will be added in the next sync!
