### ISSUE TITLE
Protofire DAO

### ISSUE THREAD

**Issue by protofivan** [safe-global/safe-ecosystem-database#89]
### Project

Protofire DAO

### Description

Reliable partner for Safe and DeFi deployment, customization & development, supporting 50+ networks

### Please provide the project scope.

Network

### Select a primary category of your project.

Infrastructure

### Select secondary categories of your project.

DeFi, SAFE, Infrastructure

### Project logo

![proto](https://github.com/safe-global/safe-ecosystem-database/assets/97111268/523bbeb6-cd30-4d25-bfea-fc243cb16dbf)

### Contact

ivan@protofire.io

### Project URL

https://protofire.io/services/safe-deployment

### Github / Dev Docs

https://github.com/protofire

### Twitter

https://twitter.com/protofire

### Primary integration

Safe Apps SDK, Core SDK, Transaction Service API, Safe Contracts

### Packages

Safe Core SDK, Safe Service Client, Transaction Service API, Safe Deployments, Safe Ethers Lib, Safe Ethers Adapter, web3-onboard, web3-react, safe-apps-wagmi, safe-apps-web3modal

### Is Safe the only Smart Account provider you are using in your project?

Yes

### Networks

Blast, Optimism, Scroll

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

Yes

**Comment by zzuziak** [comment]
Will be included in the next db sync!
