### ISSUE TITLE
Suggest a project: pier wallet

### ISSUE THREAD

**Issue by Mariowarioleoni** [safe-global/safe-ecosystem-database#92]
### Project

pier wallet

### Description

pier wallet is a **Wallet as a Service** (WaaS) provider from Switzerland, leveraging **account abstraction** to offer seamless (up to invisible) wallet experiences. Besides our own infrastructure, we leverage **Safe** technology for **multi-signature** wallets. 

### Please provide the project scope.

Core SDK Integration

### Select a primary category of your project.

Infrastructure

### Select secondary categories of your project.

Governance, Dashboard, Institutional, Accounting

### Project logo

![pier_logo-standard_black](https://github.com/safe-global/safe-ecosystem-database/assets/88843475/b1f5c8cd-cfe7-4bff-a8d7-7416f4933be2)

### Contact

mario@pierwallet.com

### Project URL

https://www.pierwallet.com/

### Github / Dev Docs

https://github.com/pier-wallet

### Twitter

https://twitter.com/pier_wallet

### Primary integration

Transaction Service API, Safe Contracts

### Packages

Safe Core SDK, Safe Ethers Lib, Safe Ethers Adapter, web3-react

### Is Safe the only Smart Account provider you are using in your project?

No

### Networks

Arbitrum, Base, Blast, Ethereum, Optimism, Polygon PoS

### Can you create a Safe via the interface?

Yes

### Can you import an existing Safe via the interface?

No

**Comment by zzuziak** [comment]
Thanks! Will be included in our next sync

**Comment by Mariowarioleoni** [comment]
FYI: Can you import an existing SAFE: yes :)
