### ISSUE TITLE
Tezoro

### ISSUE THREAD

**Issue by kamilmamin** [safe-global/safe-ecosystem-database#93]
### Project

Tezoro

### Description

Make your crypto recoverable

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

DeFi

### Select secondary categories of your project.

DeFi, Insurance, Automation

### Project logo

![Tezoro 500х500 black](https://github.com/safe-global/safe-ecosystem-database/assets/172289192/d3a23ed9-18b1-485e-9630-54bbb7f273d9)

### Value proposition

Create a smart contract that can recover your crypto if something goes wrong. 

### Contact

hello@tezoro.io

### Project URL

https://tezoro.io/

### Github / Dev Docs

https://gitlab.com/tezoro/tezoro-frontend-2.0

### Twitter

https://twitter.com/tezoroio

### Primary integration

Safe Apps SDK

### Packages

safe-apps-wagmi

### Modules / Guards

To ensure the security of the service, Tezoro uses a long list of technologies and libraries at the smart contract, front-end and back-end levels. For example, Viem and Wagmi. Tezoro was audited by Consensys Diligence and CertiK.

### Smart Accounts

Smart Accounts improve the safety of funds and the security of recovery and inheritance transactions.

### Is Safe the only Smart Account provider you are using in your project?

Yes

### Networks

Ethereum

### Can you create a Safe via the interface?

No

### Can you import an existing Safe via the interface?

Yes

**Comment by zzuziak** [comment]
Will be added with our next DB sync 👌
