### ISSUE TITLE
Suggest a project

### ISSUE THREAD

**Issue by milonite** [safe-global/safe-ecosystem-database#99]
### Project

Enso

### Description

Enso offers a unified API for interacting with DeFi protocols, and the token economy on EVM compatible chains. Building integrations with each protocol is time consuming, challenging, costly and error prone. Enso API allows developers to build once and integrate with all protocols.

### Please provide the project scope.

Safe Apps

### Select a primary category of your project.

DeFi

### Select secondary categories of your project.

Infrastructure

### Project logo

![Enso-Logo-Transparent](https://github.com/user-attachments/assets/bba8dc75-bb4c-4887-88d9-2d0a361941d8)

### Value proposition

Enso offers a unified API for interacting with DeFi protocols, and the token economy on [EVM compatible chains](https://api-docs.enso.finance/concepts/networks). Building integrations with each protocol is time consuming, challenging, costly and error prone. Enso API allows developers to build once and integrate with all protocols.

### Contact

connor@enso.finance

### Project URL

https://www.enso.finance/

### Github / Dev Docs

https://api-docs.enso.finance/

### Twitter

https://x.com/EnsoFinance

### Primary integration

Transaction Service API

### Packages

Transaction Service API

### Smart Accounts

Bundling transactions

### Is Safe the only Smart Account provider you are using in your project?

Yes

### Networks

Arbitrum, Avalanche, Base, Ethereum, Gnosis Chain, Optimism, Polygon PoS

### Can you create a Safe via the interface?

None

### Can you import an existing Safe via the interface?

None

**Comment by zzuziak** [comment]
Will be included in the next sync 👍
